// Mock Data - Tours profesionales para Ecuador

export const tourosMock = [
  {
    id_tour: 1,
    nombre: "Aventura en el Volcán Cotopaxi",
    ciudad_destino: "Latacunga",
    precio: 85.00,
    duracion: "8 horas",
    descripcion: "Explora el majestuoso Cotopaxi, uno de los volcanes activos más altos del mundo. Incluye caminata a 4,500m y vistas panorámicas increíbles.",
    latitud: "-0.9331",
    longitud: "-78.4403",
    imagen_portada: "/uploads/tour1.jpg",
    incluye: ["Transporte", "Guía profesional", "Almuerzo", "Equipo de montaña"],
    dificultad: "Moderada",
    maximo_personas: 12,
    idiomas: ["Español", "Inglés"],
    calificacion: 4.8,
    resenas: 147
  },
  {
    id_tour: 2,
    nombre: "Ruta de las Cascadas - Baños",
    ciudad_destino: "Baños",
    precio: 65.00,
    duracion: "6 horas",
    descripcion: "Descubre las cascadas más hermosas de Ecuador. Incluye saltos de agua, piscinas naturales y aventura en la selva.",
    latitud: "-1.4034",
    longitud: "-78.1242",
    imagen_portada: "/uploads/tour2.jpg",
    incluye: ["Transporte", "Guía especializado", "Almuerzo", "Fotos profesionales"],
    dificultad: "Fácil",
    maximo_personas: 15,
    idiomas: ["Español", "Inglés", "Francés"],
    calificacion: 4.9,
    resenas: 256
  },
  {
    id_tour: 3,
    nombre: "Centro Histórico de Quito",
    ciudad_destino: "Quito",
    precio: 45.00,
    duracion: "4 horas",
    descripcion: "Recorre el corazón de Quito. Visita la Basílica, Palacio de Gobierno, iglesias coloniales y plazas históricas.",
    latitud: "-0.2197",
    longitud: "-78.5099",
    imagen_portada: "/uploads/tour3.jpg",
    incluye: ["Guía historiador", "Entrada a monumentos", "Café ecuatoriano", "Mapa turístico"],
    dificultad: "Muy Fácil",
    maximo_personas: 20,
    idiomas: ["Español", "Inglés", "Alemán"],
    calificacion: 4.7,
    resenas: 189
  },
  {
    id_tour: 4,
    nombre: "Quilotoa Loop - Laguna Glaciar",
    ciudad_destino: "Latacunga",
    precio: 120.00,
    duracion: "2 días",
    descripcion: "Atardeceres espectaculares en la laguna cratérica más bella de Ecuador. Tour de aventura con campamento incluido.",
    latitud: "-0.8565",
    longitud: "-78.9231",
    imagen_portada: "/uploads/tour4.jpg",
    incluye: ["2 noches de alojamiento", "Todas las comidas", "Guía de montaña", "Equipo de camping"],
    dificultad: "Moderada",
    maximo_personas: 10,
    idiomas: ["Español", "Inglés"],
    calificacion: 4.95,
    resenas: 312
  },
  {
    id_tour: 5,
    nombre: "Galápagos - Islas Encantadas",
    ciudad_destino: "Galapagos",
    precio: 1200.00,
    duracion: "5 días",
    descripcion: "La experiencia de vida silvestre más increíble. Avistar especies únicas en el archipiélago más biodiverso del mundo.",
    latitud: "-0.3462",
    longitud: "-91.1789",
    imagen_portada: "/uploads/tour5.jpg",
    incluye: ["Vuelo a Galápagos", "4 noches crucero", "Todas las comidas", "Equipo de snorkel", "Guía naturalista"],
    dificultad: "Muy Fácil",
    maximo_personas: 16,
    idiomas: ["Español", "Inglés"],
    calificacion: 5.0,
    resenas: 587
  },
  {
    id_tour: 6,
    nombre: "Amazonía - Selva Profunda",
    ciudad_destino: "Misahuallí",
    precio: 450.00,
    duracion: "3 días",
    descripcion: "Inmersión en la selva amazónica ecuatoriana. Avistamiento de fauna, caminatas nocturnas y comunidades indígenas.",
    latitud: "-1.0340",
    longitud: "-77.6707",
    imagen_portada: "/uploads/tour6.jpg",
    incluye: ["Alojamiento lodge", "Todas las comidas", "Guía especialista", "Equipo de aventura"],
    dificultad: "Moderada",
    maximo_personas: 12,
    idiomas: ["Español", "Inglés"],
    calificacion: 4.85,
    resenas: 423
  },
  {
    id_tour: 7,
    nombre: "Otavalo - Mercado Indígena",
    ciudad_destino: "Otavalo",
    precio: 55.00,
    duracion: "5 horas",
    descripcion: "Visita el famoso mercado indígena de Otavalo. Compra artesanías tradicionales y conoce la cultura local.",
    latitud: "0.2259",
    longitud: "-78.2641",
    imagen_portada: "/uploads/tour7.jpg",
    incluye: ["Transporte", "Guía cultural", "Almuerzo típico", "Visita a talleres artesanales"],
    dificultad: "Muy Fácil",
    maximo_personas: 25,
    idiomas: ["Español", "Inglés", "Kichwa"],
    calificacion: 4.6,
    resenas: 234
  },
  {
    id_tour: 8,
    nombre: "Caminar la Línea Ecuatorial",
    ciudad_destino: "Quito",
    precio: 35.00,
    duracion: "3 horas",
    descripcion: "Experiencia única - estar en dos hemisferios simultáneamente. Museo y monumento del Mitad del Mundo.",
    latitud: "-0.0022",
    longitud: "-78.3485",
    imagen_portada: "/uploads/tour8.jpg",
    incluye: ["Entrada a museo", "Guía bilíngue", "Certificado de participación", "Refrigerio"],
    dificultad: "Muy Fácil",
    maximo_personas: 30,
    idiomas: ["Español", "Inglés", "Portugués"],
    calificacion: 4.4,
    resenas: 156
  },
  {
    id_tour: 9,
    nombre: "Surfing en Montañita",
    ciudad_destino: "Santa Elena",
    precio: 75.00,
    duracion: "4 horas",
    descripcion: "Aprende a surfear en las mejores olas de Ecuador. Clases de principiante a avanzado en la playa paradisíaca.",
    latitud: "-1.6315",
    longitud: "-80.7319",
    imagen_portada: "/uploads/tour9.jpg",
    incluye: ["Tabla de surf", "Traje de baño", "Instructor certificado", "Reflexiones en la playa"],
    dificultad: "Fácil",
    maximo_personas: 8,
    idiomas: ["Español", "Inglés"],
    calificacion: 4.7,
    resenas: 178
  },
  {
    id_tour: 10,
    nombre: "Degustación de Cacao Ecuatoriano",
    ciudad_destino: "Manabí",
    precio: 55.00,
    duracion: "4 horas",
    descripcion: "Visita una plantación de cacao y aprende el proceso de producción del mejor cacao del mundo. Degustación incluida.",
    latitud: "-0.9534",
    longitud: "-80.2403",
    imagen_portada: "/uploads/tour10.jpg",
    incluye: ["Tour de plantación", "Degustación de 5 tipos de cacao", "Almuerzo", "Productos para llevar"],
    dificultad: "Muy Fácil",
    maximo_personas: 20,
    idiomas: ["Español", "Inglés"],
    calificacion: 4.8,
    resenas: 203
  }
];

export const guiasMock = [
  {
    id: 1,
    nombre: "Carlos",
    apellido: "Montaña López",
    experiencia: 15,
    especialidad: "Montañismo y Volcanes",
    calificacion: 4.9,
    resenas: 156,
    idiomas: ["Español", "Inglés", "Alemán"],
    toursGuiados: 342,
    gananciasMes: 4200.00,
    disponible: true,
    imagen: "https://ui-avatars.com/api/?name=Carlos+Montaña&background=022b3a&color=fff&bold=true"
  },
  {
    id: 2,
    nombre: "María",
    apellido: "Fernández Ríos",
    experiencia: 12,
    especialidad: "Selva Amazónica",
    calificacion: 4.95,
    resenas: 234,
    idiomas: ["Español", "Inglés", "Francés"],
    toursGuiados: 287,
    gananciasMes: 5100.00,
    disponible: true,
    imagen: "https://ui-avatars.com/api/?name=Maria+Fernandez&background=1F7A8C&color=fff&bold=true"
  },
  {
    id: 3,
    nombre: "Juan",
    apellido: "Velasco Torres",
    experiencia: 20,
    especialidad: "Historia y Cultura",
    calificacion: 4.85,
    resenas: 198,
    idiomas: ["Español", "Inglés", "Italiano"],
    toursGuiados: 512,
    gananciasMes: 6800.00,
    disponible: true,
    imagen: "https://ui-avatars.com/api/?name=Juan+Velasco&background=bef264&color=022b3a&bold=true"
  },
  {
    id: 4,
    nombre: "Patricia",
    apellido: "Morales Soto",
    experiencia: 8,
    especialidad: "Playas y Agua",
    calificacion: 4.7,
    resenas: 89,
    idiomas: ["Español", "Inglés"],
    toursGuiados: 156,
    gananciasMes: 2800.00,
    disponible: false,
    imagen: "https://ui-avatars.com/api/?name=Patricia+Morales&background=022b3a&color=fff&bold=true"
  },
  {
    id: 5,
    nombre: "Roberto",
    apellido: "Guzmán Pérez",
    experiencia: 18,
    especialidad: "Ornitología y Fauna",
    calificacion: 4.92,
    resenas: 267,
    idiomas: ["Español", "Inglés", "Portugués"],
    toursGuiados: 421,
    gananciasMes: 5900.00,
    disponible: true,
    imagen: "https://ui-avatars.com/api/?name=Roberto+Guzman&background=1F7A8C&color=fff&bold=true"
  }
];

export const reservasMock = [
  {
    id: "RES-001",
    turista: "David Rodríguez",
    email: "david@email.com",
    tour: "Aventura en el Volcán Cotopaxi",
    idTour: 1,
    fecha: "2026-02-20",
    personas: 2,
    total: 170.00,
    estadoPago: "Pagado",
    guia: "Carlos Montaña López"
  },
  {
    id: "RES-002",
    turista: "Ana García",
    email: "ana@email.com",
    tour: "Ruta de las Cascadas - Baños",
    idTour: 2,
    fecha: "2026-03-05",
    personas: 4,
    total: 260.00,
    estadoPago: "Pendiente",
    guia: "María Fernández Ríos"
  },
  {
    id: "RES-003",
    turista: "Pedro López",
    email: "pedro@email.com",
    tour: "Centro Histórico de Quito",
    idTour: 3,
    fecha: "2026-02-28",
    personas: 3,
    total: 135.00,
    estadoPago: "Pagado",
    guia: "Juan Velasco Torres"
  },
  {
    id: "RES-004",
    turista: "Isabella Marconi",
    email: "isabella@email.com",
    tour: "Quilotoa Loop - Laguna Glaciar",
    idTour: 4,
    fecha: "2026-03-15",
    personas: 6,
    total: 720.00,
    estadoPago: "Pendiente",
    guia: "Carlos Montaña López"
  },
  {
    id: "RES-005",
    turista: "Michael Smith",
    email: "msmith@email.com",
    tour: "Galápagos - Islas Encantadas",
    idTour: 5,
    fecha: "2026-04-10",
    personas: 2,
    total: 2400.00,
    estadoPago: "Cancelado",
    guia: "Roberto Guzmán Pérez"
  }
];
